### ISSUE TITLE
[feature request] Revisit TAGS file automatically

### ISSUE THREAD

**Issue by marcinant** [jixiuf/helm-etags-plus#13]
Hi!

Thank you for this package. It's really usefull. However there is one thing which is annoying for me. Every time I rebuild TAGS I have to confirm that I want to reload TAGS file.
It could be great to have an option to revisit TAGS file automatically.

**Comment by jixiuf** [comment]
try (setq-default tags-revert-without-query  t),  if doesnot work ,

**Comment by jixiuf** [comment]
i will close this issuce ,feel free to reopen.
