### ISSUE TITLE
ctags-update always sets recursive

### ISSUE THREAD

**Issue by fommil** [jixiuf/helm-etags-plus#14]
I noticed major performance problems running ctags-update on a file in a very large project and discovered that you're setting the recursive flag. I'm pretty sure that shouldn't be set when updating just one file. This made in also setting a bunch of flags that I don't want (I have everything in my project .ctags).

**Comment by fommil** [comment]
Hmm, on closer inspection, ctags update is running update for everything. I thought it was just doing an update on the current file. Thin may not be the functionality that I thought it was.

**Comment by jixiuf** [comment]
ctags  do not support updating single file . 
you could set ctags-update-delay-seconds a lager value .
maybe you could try https://github.com/syohex/emacs-helm-gtags
gtags support update single file .

**Comment by fommil** [comment]
That's the first compelling reason I've heard the switch to gtags, thanks!

**Comment by jixiuf** [comment]
try my fork of emacs-helm-gtags https://github.com/jixiuf/emacs-helm-gtags 
it almost have the same interface

**Comment by fommil** [comment]
I've decided to just do manual updates of the TAGS file.
